readingDataPointsFilters:
  - IdentityDataPointsFilter

referenceDataPointsFilters:
  - IdentityDataPointsFilter

matcher:
  KDTreeMatcher

outlierFilters:
  - NullOutlierFilter

errorMinimizer:
  IdentityErrorMinimizer

transformationCheckers:
  - CounterTransformationChecker:
      maxIterationCount: 1

inspector:
  NullInspector

logger:
  NullLogger