matcher:
  KDTreeMatcher:
    knn: 5
    maxDist: 2.0
    epsilon: 1

outlierFilters:
  - TrimmedDistOutlierFilter:
     ratio: 0.8
  - SurfaceNormalOutlierFilter:
     maxAngle: 0.42

errorMinimizer:
  PointToPlaneErrorMinimizer:
     force4DOF: 1

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 2
  - CounterTransformationChecker:
      maxIterationCount: 100
  - BoundTransformationChecker:
      maxRotationNorm: 1.1
      maxTranslationNorm: 15.00

inspector:
  NullInspector

logger:
  NullLogger
